services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    command: ["--query.max-clock-skew-adjustment", "500ms"]
    ports:
      - "127.0.0.1:16686:16686"
    environment:
      - LOG_LEVEL=info

  livy:
    image: livy-image
    build: .
    environment:
      JAVA_TOOL_OPTIONS: '-javaagent:/tmp/opentelemetry-javaagent.jar -Dotel.javaagent.extensions=/tmp/otel-livy-extension-0.8.jar'
      #JAVA_TOOL_OPTIONS: '-javaagent:/tmp/applicationinsights-agent.jar -Dotel.javaagent.extensions=/tmp/otel-livy-extension-0.8.jar -Dotel.instrumentation.apache-livy.enabled=true'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://jaeger:4318'
      OTEL_SERVICE_NAME: 'livy-app'
      OTEL_METRICS_EXPORTER: 'none'
      OTEL_LOGS_EXPORTER: 'none'
    #secrets:
    #  - applicationinsights_connection_string
    command: ["/tmp/incubator-livy/bin/livy-server"]
    ports:
      - "127.0.0.1:8998:8998"

#secrets:
  #applicationinsights_connection_string:
    #file: ./conf/applicationinsights-connection-string.txt
